version: "3"
services:
  employee-management: 
    build: .
    image: employee-management:latest
    container_name: ems
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/test?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      WAIT_HOST: mysql:3306
    depends_on:
      - docker-mysql  
  docker-mysql:
    restart: always
    image: mysql
    container_name: docker-mysql
    environment: 
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES\""
      interval: 2s
      timeout: 20s
      retries: 10