version: "3"
services:
  employee-management: 
    build: .
    image: employee-management
    container_name: ems
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - docker-postgres  
  docker-postgres:
    restart: always
    image: postgres
    container_name: docker-postgress
    environment: 
      POSTGRES_DATABASE: d8p67up31vfg1i
      POSTGRES_USER: mpxghihkjgsvzk
      POSTGRES_PASSWORD: cc0a95dcbd79f26ca7072162a4a727b7db94746bd9213d4c0589d755b3ad2521
    ports:
      - "5432:5432"
      