version: "3"
services:
  employee-management: 
    build: .
    image: employee-management
    container_name: ems
    restart: always
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - docker-postgres  
  docker-postgres:
    restart: always
    image: postgres
    container_name: docker-postgress
    environment: 
      POSTGRES_DATABASE: test
      POSTGRES_USER: rashed
      POSTGRES_PASSWORD: rashed
    ports:
      - "5432:5432"
      